[default]
extend-words = { edn = "edn", ba = "ba", ths = "ths", shs = "shs", nd = "nd", noice = "noice", pn = "pn", thn = "thn", unparented = "unparented", typ = "typ" }

[files]
extend-exclude = [
  "infra/services/cloudflare/*.tf",
  "applications/neovim/lua/**/*.lua",
]
